site_name: Zoe
repo_name: Zoe
repo_url: https://github.com/adevinta/zoe
site_description: "Zoe: The Kafka companion"
site_author: Adevinta
remote_branch: gh-pages

copyright: 'Copyright (c) 2020 Adevinta'

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'indigo'

nav:
  - 'Install': install.md
  - 'Tutorials':
      - 'A simple example': tutorials/simple.md
      - 'Zoe with Avro': tutorials/avro.md
