apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    context: zoe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: broker
  template:
    metadata:
      labels:
        service: broker
    spec:
      containers:
        - env:
            - name: CONFLUENT_METRICS_ENABLE
              value: "true"
            - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
              value: broker:9092
            - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
              value: "1"
            - name: CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: CONFLUENT_SUPPORT_CUSTOMER_ID
              value: anonymous
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:5.0.0
          name: broker
          ports:
            - containerPort: 9092
            - containerPort: 29092
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: "0.5"
              memory: "1G"
      hostname: broker
      restartPolicy: Always
