apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    service: zookeeper
    context: zoe-demo
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    service: zookeeper
