name: Publish runtimeless packages

on:
  release:
    types: ["published"]

jobs:
  release-runtimeless:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set upload url
        id: fetch_release_data
        run: |
          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: ./scripts/package-tar-without-runtime.sh
        
      - name: Upload tar package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }} 
          asset_path: packages/zoe-cli.tar.gz
          asset_name: zoe-cli.tar.gz
          asset_content_type: application/zip
          
      - name: Upload zip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: packages/zoe-cli.zip
          asset_name: zoe-cli.zip
          asset_content_type: application/zip
