name: Publish release packages

on:
  release:
    types: ["published"]

jobs:

  release-runtimeless:
    name: Publish packages without runtime

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '100'

      - name: set upload url
        id: fetch_release_data
        run: |
          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          ./dev/scripts/clean.sh
          ./dev/scripts/build.sh

      - name: Package
        id: package
        run: |
          ./dev/scripts/packages-without-runtime.sh

          # retrieve packages
          zip_package=$(ls -t packages/zoe-*.zip | head -n 1)
          tar_package=$(ls -t packages/zoe-*.tar.gz | head -n 1)

          # ensure packages are generated
          [[ -z "${zip_package}" || -z "${tar_package}" ]] && \
            { echo "one of the packages not found : (zip: ${tar_package} | tar: ${tar_package})"; exit 1; }

          echo "::set-output name=zip_package_path::${zip_package}"
          echo "::set-output name=zip_package_name::$(basename ${zip_package})"
          echo "::set-output name=tar_package_path::${tar_package}"
          echo "::set-output name=tar_package_name::$(basename ${tar_package})"

      - name: Upload zip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.zip_package_path }}
          asset_name: ${{ steps.package.outputs.zip_package_name }}
          asset_content_type: application/zip

      - name: Upload tar package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.tar_package_path }}
          asset_name: ${{ steps.package.outputs.tar_package_name }}
          asset_content_type: application/zip

  release-runtimefull:

    name: Publish packages with runtime

    strategy:
      matrix:
        package:
          - type: deb
            os: ubuntu-latest
          - type: rpm
            os: ubuntu-latest

    runs-on: ${{ matrix.package.os }}

    env:
      target: ${{ matrix.package.type }}

    steps:
      - uses: actions/checkout@v2

      - name: set upload url
        id: fetch_release_data
        run: |
          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          ./dev/scripts/clean.sh
          ./dev/scripts/build.sh

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14-ea
          java-package: jdk
          architecture: x64

      - name: Package
        id: package
        run: |
          ./dev/scripts/packages-with-runtime.sh ${target}

          package_path=$(ls -t packages/zoe*.${target} | head -n 1)
          package_name=$(basename "$package_path")

          echo "::set-output name=package_path::$package_path"
          echo "::set-output name=package_name::$package_name"

      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.package_path }}
          asset_name: ${{ steps.package.outputs.package_name }}
          asset_content_type: application/zip
