name: Publish runtimeless packages

on:
  release:
    types: ["published"]

jobs:

  release-runtimeless:
    name: Publish packages without runtime

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set upload url
        id: fetch_release_data
        run: |
          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          ./scripts/clean.sh
          ./scripts/build.sh

      - name: Package
        run: ./scripts/packages-without-runtime.sh

      - name: Upload tar package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: packages/zoe-cli.tar.gz
          asset_name: zoe-cli.tar.gz
          asset_content_type: application/zip

      - name: Upload zip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: packages/zoe-cli.zip
          asset_name: zoe-cli.zip
          asset_content_type: application/zip

  release-runtimefull:

    name: Publish packages with runtime

    strategy:
      matrix:
        package:
          - type: deb
            os: ubuntu-latest
          - type: rpm
            os: ubuntu-latest
#          - type: deb
#            os: macos-latest


    runs-on: ${{ matrix.package.os }}

    env:
      target: ${{ matrix.package.type }}

    steps:
      - uses: actions/checkout@v2

      - name: set upload url
        id: fetch_release_data
        run: |
          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
          RELEASE_TAG=$(jq -r '.release.tag_name' ${GITHUB_EVENT_PATH})
          echo "::set-output name=upload_url::$UPLOAD_URL"
          echo "::set-output name=release_tag::$RELEASE_TAG"

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          ./scripts/clean.sh
          ./scripts/build.sh

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14-ea
          java-package: jdk
          architecture: x64

      - name: Package
        id: package
        env:
          release_tag: ${{ steps.fetch_release_data.outputs.release_tag }}
        run: |
          ./scripts/packages-with-runtime.sh ${target} ${release_tag:1}
          package_path=$(ls -t packages/zoe*.${target} | head -n 1)
          package_name=$(basename "$package_path")
          echo "::set-output name=package_path::$package_path"
          echo "::set-output name=package_name::$package_name"

      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.package_path }}
          asset_name: ${{ steps.package.outputs.package_name }}
          asset_content_type: application/zip
